version: "3.5"
 
services:
  ratings:
    build: .
    container_name: ratings
    ports:
      - "8080:8080"
    environment:
      SERVICE_VERSION: v2
      MONGO_DB_URL: mongodb://mongodb:27017/ratings
      MONGO_DB_USERNAME: ratings
      MONGO_DB_PASSWORD: CHANGEME
  mongodb:
    container_name: mongodb
    image: bitnami/mongodb:5.0.6-debian-10-r46
    volumes:
      - "./databases:/docker-entrypoint-initdb.d"
    environment:
      MONGODB_ROOT_PASSWORD: CHANGEME
      MONGODB_EXTRA_USERNAMES: ratings
      MONGODB_EXTRA_PASSWORDS: CHANGEME
      MONGODB_EXTRA_DATABASES: ratings